baseURL: https://eens-en.netlify.app
title: "Extra Ecclesia Nulla Salus"

defaultContentLanguage: en
defaultContentLanguageInSubdir: false 
paginate: 20
paginatePath: "page"
ignoreFiles:
  - "(?i)/\\.hide/$"
markup:
  goldmark:
    renderer:
      unsafe: true

