baseURL: https://eens.netlify.app
title: "Extra Ecclesia Nulla Salus"

defaultContentLanguage: en
defaultContentLanguageInSubdir: false 
paginate: 20
paginatePath: "page"
ignoreFiles:
  - "(?i)/\\.hide/$"
markup:
  goldmark:
    renderer:
      unsafe: true

languages:
  en:
    languageCode: en-US
    languageName: English
    weight: 1
    title: My Site in English
    params:
      description: This is my site in English
  fr:
    languageCode: fr-FR
    languageName: Français
    weight: 2
    title: Mon Site en Français
    params:
      description: Ceci est mon site en français

params:
  # Shared parameters for all languages

markup:
  # Markup configuration
