defaultContentLanguageInSubdir: false 
paginate: 20
paginatePath: "page"
ignoreFiles:
  - "(?i)/\\.hide/$"

# Configuration for Hugo using Goldmark with all extensions
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
