baseURL: https://example.com
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
  en:
    languageCode: en-US
    languageName: English
    weight: 1
    title: My Site in English
    params:
      description: This is my site in English

  fr:
    languageCode: fr-FR
    languageName: Français
    weight: 2
    title: Mon Site en Français
    params:
      description: Ceci est mon site en français

params:
  # Shared parameters for all languages

markup:
  # Markup configuration
