baseURL: https://eens-en.netlify.app
title: "Extra Ecclesia Nulla Salus"

defaultContentLanguageInSubdir: false 
paginate: 20
paginatePath: "page"
ignoreFiles:
  - "(?i)/\\.hide/$"

social:
  twitter: "BroMatthewCap"




